version: "1"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    restart: always
    environment:
      env_file: .env
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648"
    ports:
      - 15672:15672
      - "${RABBITMQ_PORT}:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
  postgresql:
    container_name: customers-database
    image: postgres:16
    environment:
      env_file: .env
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgresdata: